sonar.projectKey=SecureCloud-K8s-DevSecOps
sonar.projectName=SecureCloud-K8s-DevSecOps
sonar.sources=.
sonar.sourceEncoding=UTF-8

# node_modules va boshqa keraksiz fayllarni skanerlashdan chiqarib tashlash
sonar.exclusions=**/node_modules/**, **/dist/**, **/trivy*.txt, **/*.docx, **/Manifest-file/**
